"""Static, dependency-free client for the live recommendation dashboard."""

from __future__ import annotations


DASHBOARD_HTML: str = """<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>오늘의 투자 인사이트</title>
<style>
:root{color-scheme:dark}body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#07111e;color:#edf3ff}main{max-width:1100px;margin:auto;padding:32px}button{background:#4f8cff;color:white;border:0;border-radius:8px;padding:12px 18px;font-weight:700;cursor:pointer}button:disabled{background:#5a6d86;cursor:wait}.run-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.collection-size{display:flex;gap:6px;border:0;margin:0;padding:0}.collection-size input{position:absolute;opacity:0}.collection-size label{border:1px solid #385474;border-radius:8px;padding:8px 10px;color:#c7d8ee;cursor:pointer;font-size:14px}.collection-size input:checked+label{border-color:#4f8cff;background:#203b61;color:#fff}.collection-size input:focus-visible+label{outline:2px solid #83b2ff;outline-offset:2px}.panel{background:#101d2d;border:1px solid #253852;border-radius:12px;padding:20px;margin:18px 0}.progress-meta{display:flex;gap:20px;flex-wrap:wrap;color:#c7d8ee}.progress-track{height:10px;background:#233650;border-radius:999px;overflow:hidden;margin:16px 0}.progress-fill{height:100%;background:linear-gradient(90deg,#4f8cff,#67d5b5);transition:width .3s}.stage-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px;padding:0;list-style:none}.stage{border:1px solid #29415f;border-radius:9px;background:#132238}.stage summary{padding:12px;cursor:pointer;list-style:none}.stage summary::-webkit-details-marker{display:none}.stage-name{font-weight:700}.stage-state{display:inline-block;min-width:62px;margin-right:7px;font-size:12px;color:#aec0d8}.stage.done .stage-state{color:#7ae5a1}.stage.active{border-color:#4f8cff;box-shadow:0 0 0 1px #4f8cff}.stage.active .stage-state{color:#83b2ff}.stage-guide{padding:0 12px 12px;color:#c7d8ee;font-size:14px;line-height:1.55}.stage-guide p{margin:6px 0}.stage-guide strong{color:#fff}.timeline li{margin:8px 0}.cards{display:flex;gap:14px;overflow-x:auto}.card{min-width:260px;background:#17263a;border-radius:10px;padding:16px}.analysis-card{min-width:310px}.analysis-card h3{margin:8px 0}.analysis-card p{margin:8px 0}.badge{display:inline-block;border-radius:999px;background:#29415f;padding:3px 8px;margin:2px 4px 2px 0;font-size:12px}.empty{color:#aec0d8}.buy{color:#7ae5a1}.sell{color:#ff8c9b}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #29415f;text-align:left}@media(max-width:600px){main{padding:18px}.stage-list{grid-template-columns:1fr}}
</style></head><body><main>
<h1>오늘의 투자 인사이트</h1><p>실제 뉴스·공시를 수집하고 LangGraph 분석을 거쳐 Policy 기반 종목 후보를 생성합니다.</p>
<div class="run-controls"><button id="run">오늘의 뉴스를 기준으로 추천받기</button><fieldset class="collection-size" id="collection-size"><legend class="empty">분석 건수</legend><input type="radio" id="size-10" name="collection-size" value="10" checked><label for="size-10">적게 · 10건</label><input type="radio" id="size-25" name="collection-size" value="25"><label for="size-25">중간 · 25건</label><input type="radio" id="size-50" name="collection-size" value="50"><label for="size-50">많이 · 50건</label><input type="radio" id="size-100" name="collection-size" value="100"><label for="size-100">최대 · 100건</label></fieldset><fieldset class="collection-size" id="theme-filter"><legend class="empty">투자 테마</legend><input type="checkbox" id="theme-semiconductor" value="semiconductor"><label for="theme-semiconductor">반도체</label><input type="checkbox" id="theme-ai" value="artificial_intelligence"><label for="theme-ai">AI</label><input type="checkbox" id="theme-renewable-energy" value="renewable_energy"><label for="theme-renewable-energy">대체에너지</label></fieldset><fieldset class="collection-size" id="topic-filter"><legend class="empty">뉴스 주제</legend><input type="checkbox" id="topic-earnings" value="earnings"><label for="topic-earnings">실적</label><input type="checkbox" id="topic-policy" value="policy"><label for="topic-policy">정책</label><input type="checkbox" id="topic-supply-chain" value="supply_chain"><label for="topic-supply-chain">공급망</label><input type="checkbox" id="topic-technology" value="technology"><label for="topic-technology">기술</label></fieldset></div>
<section class="panel"><h2>전체 진행 상황</h2><div class="progress-meta"><span id="progress-summary">실행 전</span><span id="elapsed">경과 시간 0초</span><span id="connection">실행을 시작하면 상태를 확인합니다.</span></div><div class="progress-track"><div id="progress-fill" class="progress-fill"></div></div><ol id="stages" class="stage-list"></ol></section>
<section class="panel"><h2>실시간 작업 기록</h2><ol id="timeline" class="timeline"></ol></section>
<section class="panel"><h2>전체 수집 뉴스 분석</h2><div id="analyses" class="cards"><p class="empty">추천 실행 후 전체 뉴스의 분석 과정을 표시합니다.</p></div></section>
<section class="panel"><h2>후보 제외 진단</h2><div id="diagnostics"><p class="empty">추천 실행 후 후보가 점수화되지 않은 이유를 표시합니다.</p></div></section>
<section class="panel"><h2>선택된 뉴스</h2><div id="cards" class="cards"><p class="empty">추천 실행 후 선택된 뉴스를 표시합니다.</p></div></section>
<section class="panel"><h2>매수 · 판매 추천</h2><table><thead><tr><th>종목</th><th>코드</th><th>점수</th><th>추천</th><th>근거</th></tr></thead><tbody id="recommendations"><tr><td colspan="5" class="empty">추천 실행 후 결과를 표시합니다.</td></tr></tbody></table></section>
<script>
const timeline=document.querySelector('#timeline'),cards=document.querySelector('#cards'),analyses=document.querySelector('#analyses'),diagnostics=document.querySelector('#diagnostics'),recommendations=document.querySelector('#recommendations'),button=document.querySelector('#run'),collectionSize=document.querySelector('#collection-size'),themeFilter=document.querySelector('#theme-filter'),topicFilter=document.querySelector('#topic-filter'),stagesElement=document.querySelector('#stages'),summaryElement=document.querySelector('#progress-summary'),elapsedElement=document.querySelector('#elapsed'),connectionElement=document.querySelector('#connection'),progressFill=document.querySelector('#progress-fill');
const stages=[
 ['collect','뉴스·공시 수집','Naver News와 DART에서 기간·카테고리·건수 조건에 맞는 원본 게시물을 수집하고 공통 Article 형식으로 정규화합니다.','출처별 수집 실패는 다른 출처 결과를 유지하는 부분 실패로 기록합니다.'],
 ['directory','종목 기준정보 준비','KRX 상장사 스냅샷을 준비해 이후 이벤트와 기업을 일관된 기준으로 연결할 준비를 합니다.','종목 매핑은 이 단계의 스냅샷을 사용하며, LLM이 임의로 종목을 추론하지 않습니다.'],
 ['evaluate','분석 대상 점검','LLM 호출 전 기사 제목·본문의 최소 구조를 점검합니다.','빈 제목·본문 또는 최소 본문 길이 미달 기사는 분석 대상에서 제외합니다. 관련성·투자 판단은 여기서 하지 않습니다.'],
 ['extract','이벤트 추출','허용된 기사에서 회사·산업·시장에 의미 있는 구조화 이벤트와 안전한 요약을 추출합니다.','Parser가 형식과 필수 값을 검증합니다. LLM은 이벤트 관측만 하며 최종 추천을 내리지 않습니다.'],
 ['screen','AI Screening','각 이벤트의 관련성·중요도·신뢰도를 0~100으로 관측하고, 교차검증 필요 여부와 근거를 남깁니다.','Policy가 관련성 또는 중요도 40점 미만은 REJECT, 교차검증 필요 시 REVIEW, 세 점수 모두 70점 이상은 ACCEPT로 결정합니다. 나머지는 REVIEW입니다.'],
 ['cross_validate','교차 검증','REVIEW 이벤트를 다른 기사 증거와 비교하여 지지·충돌·무관 관계를 관측합니다.','LLM은 관계와 근거만 관측합니다. Policy가 독립 출처와 증거 상태를 계산해 VERIFIED 등 상태를 결정합니다.'],
 ['resolve','이벤트·기업 연결','스크리닝과 교차검증 결과를 동일 이벤트 및 KRX 기업 스냅샷에 연결합니다.','Resolve Policy가 최종 ACCEPT·REVIEW·REJECT를 결정하며, 모호하거나 미해결 기업은 이후 종목 근거에서 제외됩니다.'],
 ['analyze','영향 분석','확정된 이벤트가 기업·산업·시장에 미치는 영향을 분석합니다.','영향 관측은 분석기 책임이며, 매수·매도 결론은 이 단계에서 만들지 않습니다.'],
 ['aggregate','근거 집계','기업별 영향 분석을 모아 종목 평가에 쓸 근거 묶음을 만듭니다.','같은 기업의 유효 근거를 결합하되 원본 이벤트 연결을 보존합니다.'],
 ['score','종목 점수 계산','집계된 근거를 결정적 점수 전략으로 종목 점수로 변환합니다.','점수는 LLM의 매매 지시가 아니라 정책에 전달할 정량 근거입니다.'],
 ['recommend','추천 결정','점수와 정책 임계값을 적용해 매수·관망·주의 등 최종 추천을 만듭니다.','최종 투자 추천은 LLM이 아닌 deterministic Recommendation Policy가 결정합니다.'],
 ['select_candidates','후보 선택','추천 결과에서 표시할 투자 후보를 선택하고 최종 화면용 결과를 구성합니다.','이미 결정된 점수와 추천을 바꾸지 않고, 후보 표시용 내부 선택만 수행합니다.']
];
const progress={completed:0,total:stages.length,active:null,status:'idle',startedAt:null,lastHeartbeat:null};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const empty=message=>`<p class="empty">${escapeHtml(message)}</p>`;const emptyRow=message=>`<tr><td colspan="5" class="empty">${escapeHtml(message)}</td></tr>`;const safeHref=value=>{try{const url=new URL(value);return url.protocol==='https:'||url.protocol==='http:'?escapeHtml(url.href):'#'}catch(_){return '#'}};
const formatElapsed=milliseconds=>{const seconds=Math.floor(milliseconds/1000),minutes=Math.floor(seconds/60);return minutes?`${minutes}분 ${seconds%60}초`:`${seconds}초`};
const renderProgress=()=>{const remaining=Math.max(progress.total-progress.completed,0);const percent=progress.total?progress.completed/progress.total*100:0;const summary=progress.status==='running'?`${progress.completed}/${progress.total} 단계 완료 · ${remaining}단계 남음`:progress.status==='completed'?'전체 단계 완료':progress.status==='failed'?`실행 실패 · ${progress.completed}/${progress.total} 단계 완료`:'실행 전';progressFill.style.width=`${percent}%`;summaryElement.textContent=summary;elapsedElement.textContent=`경과 시간 ${progress.startedAt?formatElapsed(Date.now()-progress.startedAt):'0초'}`;connectionElement.textContent=progress.lastHeartbeat?`서버 확인 ${new Date(progress.lastHeartbeat).toLocaleTimeString('ko-KR')} · ${progress.active?'현재 단계 처리 중':progress.status==='failed'?'중단됨':'완료'}`:'실행을 시작하면 상태를 확인합니다.';stagesElement.innerHTML=stages.map(([key,name,work,criteria],index)=>{const state=index<progress.completed?'done':key===progress.active&&progress.status==='running'?'active':'waiting';const stateText=state==='done'?'완료':state==='active'?'진행 중':'대기';return `<li><details class="stage ${state}" ${state==='active'?'open':''}><summary><span class="stage-state">${stateText}</span><span class="stage-name">${index+1}. ${escapeHtml(name)}</span></summary><div class="stage-guide"><p><strong>작업:</strong> ${escapeHtml(work)}</p><p><strong>기준:</strong> ${escapeHtml(criteria)}</p></div></details></li>`}).join('')};
setInterval(()=>{if(progress.status==='running')renderProgress()},1000);renderProgress();
const setRunControlsDisabled=disabled=>{for(const group of [collectionSize,themeFilter,topicFilter])for(const input of group.querySelectorAll('input'))input.disabled=disabled};
const reset=status=>{button.disabled=false;button.textContent='오늘의 뉴스를 기준으로 추천받기';setRunControlsDisabled(false);progress.status=status;renderProgress()};
const updateAnalyses=items=>{for(const item of items)analysisById.set(item.id,item);renderAnalyses()};const analysisById=new Map();
const renderAnalyses=()=>{const items=[...analysisById.values()];analyses.innerHTML=items.length?items.map(item=>{const events=item.event_titles.length?item.event_titles.map(title=>`<span class="badge">${escapeHtml(title)}</span>`).join(''):'<span class="badge">이벤트 없음</span>';const metrics=item.relevance===null?'':`<p>관련성 ${item.relevance} · 중요도 ${item.importance} · 신뢰도 ${item.credibility}</p>`;const scorecard=item.scorecard?`<p>세부 점수 · 테마 직접성 ${item.scorecard.theme_directness} · 주제 일치 ${item.scorecard.topic_match} · 시장 전파 ${item.scorecard.market_transmission_path}</p><p>영향 크기 ${item.scorecard.impact_magnitude} · 파급도 ${item.scorecard.scope_and_spillover} · 시간 민감도 ${item.scorecard.time_sensitivity}</p><p>출처 권위 ${item.scorecard.source_authority} · 근거 구체성 ${item.scorecard.evidence_specificity} · 교차확인/불확실성 ${item.scorecard.corroboration_and_uncertainty}</p>`:'';const reasons=item.reasons.length?`<p>${item.reasons.map(escapeHtml).join(' · ')}</p>`:'';const validation=item.validation_status?`<p>교차검증: ${escapeHtml(item.validation_status)}</p>`:'';const evidence=item.event_evidence.length?item.event_evidence.map(event=>`<div class="evidence"><h4>${escapeHtml(event.event_title)}</h4>${event.quotes.map(quote=>`<blockquote>문단 ${escapeHtml(quote.paragraph_index)}: ${escapeHtml(quote.quote)}</blockquote>`).join('')}<a href="${safeHref(event.source_url)}" target="_blank" rel="noreferrer">원문 보기</a></div>`).join(''):'';return `<article class="card analysis-card"><small>${escapeHtml(item.source)}</small><h3>${escapeHtml(item.title)}</h3><p><strong>${escapeHtml(item.status)}</strong></p>${item.summary?`<p>${escapeHtml(item.summary)}</p>`:''}<div>${events}</div>${evidence}${metrics}${scorecard}${reasons}${validation}</article>`}).join(''):empty('수집된 뉴스가 없습니다.')};
const renderDiagnostics=value=>{if(!value){diagnostics.innerHTML=empty('후보 제외 진단을 만들지 못했습니다.');return}const rows=[['실패한 이벤트 추출 배치',value.failed_extraction_batches],['형식 오류로 제외된 추출 항목',value.malformed_extraction_items],['영향 관측이 없는 승인 이벤트',value.events_without_impact_observations],['생성된 영향 관측',value.total_impact_observations],['점수 반영 가능 영향',value.eligible_impact_observations],['기업 미해결로 제외',value.unresolved_company_exclusions],['기업 식별자 누락으로 제외',value.missing_company_identity_exclusions],['검증 미달 REVIEW로 제외',value.review_not_verified_exclusions],['영향 방향 미확정으로 제외',value.unknown_direction_exclusions],['점수화된 종목',value.scored_company_count]];diagnostics.innerHTML=`<table><thead><tr><th>단계별 판단</th><th>건수</th></tr></thead><tbody>${rows.map(([label,count])=>`<tr><td>${escapeHtml(label)}</td><td>${escapeHtml(count)}</td></tr>`).join('')}</tbody></table>`};
async function load(runId){const response=await fetch(`/api/runs/${runId}`);if(!response.ok)throw new Error('result_load_failed');const data=await response.json();analysisById.clear();updateAnalyses(data.analyses);renderDiagnostics(data.statistics.impact_diagnostics);cards.innerHTML=data.news_cards.length?data.news_cards.map(news=>`<article class="card"><small>${escapeHtml(news.source)}</small><h3>${escapeHtml(news.title)}</h3><p>${escapeHtml(news.excerpt)}</p><a href="${escapeHtml(news.url)}" target="_blank" rel="noreferrer">원문 보기</a></article>`).join(''):empty('선택된 뉴스가 없습니다.');recommendations.innerHTML=data.recommendations.length?data.recommendations.map(item=>`<tr><td>${escapeHtml(item.company_name)}</td><td>${escapeHtml(item.ticker||'-')}</td><td>${escapeHtml(item.score)}</td><td class="${item.action.includes('buy')?'buy':item.action.includes('sell')?'sell':''}">${escapeHtml(item.action)}</td><td>${escapeHtml(item.reason_code)}</td></tr>`).join(''):emptyRow('현재 정책 기준을 통과한 추천 종목이 없습니다.')}
button.onclick=async()=>{const selectedSize=Number(collectionSize.querySelector('input:checked').value),selectedThemes=[...themeFilter.querySelectorAll('input:checked')].map(input=>input.value),selectedTopics=[...topicFilter.querySelectorAll('input:checked')].map(input=>input.value);timeline.innerHTML='';analysisById.clear();renderAnalyses();diagnostics.innerHTML=empty('후보 제외 사유를 집계하고 있습니다.');cards.innerHTML=empty('뉴스를 수집하고 있습니다.');recommendations.innerHTML=emptyRow('추천 분석을 진행하고 있습니다.');button.disabled=true;button.textContent='추천 분석 중…';setRunControlsDisabled(true);progress.completed=0;progress.total=stages.length;progress.active='collect';progress.status='running';progress.startedAt=Date.now();progress.lastHeartbeat=Date.now();renderProgress();try{const response=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limit:selectedSize,themes:selectedThemes,topics:selectedTopics})});if(!response.ok)throw new Error('run_start_failed');const {run_id:runId}=await response.json();let terminal=false;const source=new EventSource(`/api/runs/${runId}/events`);for(const name of ['collecting','collected','directory','workflow_started','workflow','heartbeat','completed','failed'])source.addEventListener(name,async event=>{const data=JSON.parse(event.data);progress.completed=data.completed_stage_count;progress.total=data.total_stage_count;progress.active=data.active_stage;progress.lastHeartbeat=Date.now();renderProgress();if(data.type!=='heartbeat')timeline.insertAdjacentHTML('beforeend',`<li>${escapeHtml(data.message)}</li>`);if(data.analyses.length)updateAnalyses(data.analyses);if(data.type==='completed'){terminal=true;progress.active=null;progress.completed=progress.total;source.close();try{await load(runId)}catch(_){cards.innerHTML=empty('결과를 불러오지 못했습니다.');recommendations.innerHTML=emptyRow('결과를 다시 실행해 주세요.')}reset('completed')}if(data.type==='failed'){terminal=true;source.close();const detail=`중단 단계: ${data.failure_stage||data.active_stage||'-'} · 오류: ${data.error_type||'-'} · 시도: ${data.failure_attempts||1}/3`;cards.innerHTML=empty(`뉴스 분석이 완료되지 않았습니다. ${detail}`);recommendations.innerHTML=emptyRow(detail);reset('failed')}});source.onerror=()=>{if(!terminal){source.close();cards.innerHTML=empty('실시간 연결이 끊겼습니다.');recommendations.innerHTML=emptyRow('다시 실행해 주세요.');connectionElement.textContent='실시간 연결이 끊겼습니다.';reset('failed')}}}catch(_){cards.innerHTML=empty('추천 실행을 시작하지 못했습니다.');recommendations.innerHTML=emptyRow('잠시 후 다시 시도해 주세요.');reset('failed')}};
</script></main></body></html>"""
