"""Static, dependency-free client for the live recommendation dashboard."""

from __future__ import annotations


DASHBOARD_HTML: str = """<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>오늘의 투자 인사이트</title>
<style>
body{font-family:system-ui;margin:0;background:#07111e;color:#edf3ff}main{max-width:1100px;margin:auto;padding:32px}button{background:#4f8cff;color:white;border:0;border-radius:8px;padding:12px 18px;font-weight:700}button:disabled{background:#5a6d86}.panel{background:#101d2d;border:1px solid #253852;border-radius:12px;padding:20px;margin:18px 0}.timeline li{margin:8px 0}.cards{display:flex;gap:14px;overflow-x:auto}.card{min-width:260px;background:#17263a;border-radius:10px;padding:16px}.analysis-card{min-width:310px}.analysis-card h3{margin:8px 0}.analysis-card p{margin:8px 0}.badge{display:inline-block;border-radius:999px;background:#29415f;padding:3px 8px;margin:2px 4px 2px 0;font-size:12px}.empty{color:#aec0d8}.buy{color:#7ae5a1}.sell{color:#ff8c9b}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #29415f;text-align:left}
</style></head><body><main>
<h1>오늘의 투자 인사이트</h1><p>실제 뉴스·공시를 수집하고 LangGraph 분석을 거쳐 Policy 기반 종목 후보를 생성합니다.</p>
<button id="run">오늘의 뉴스를 기준으로 추천받기</button>
<section class="panel"><h2>실시간 작업</h2><ol id="timeline" class="timeline"></ol></section>
<section class="panel"><h2>전체 수집 뉴스 분석</h2><div id="analyses" class="cards"><p class="empty">추천 실행 후 전체 뉴스의 분석 과정을 표시합니다.</p></div></section>
<section class="panel"><h2>선택된 뉴스</h2><div id="cards" class="cards"><p class="empty">추천 실행 후 선택된 뉴스를 표시합니다.</p></div></section>
<section class="panel"><h2>매수 · 판매 추천</h2><table><thead><tr><th>종목</th><th>코드</th><th>점수</th><th>추천</th><th>근거</th></tr></thead><tbody id="recommendations"><tr><td colspan="5" class="empty">추천 실행 후 결과를 표시합니다.</td></tr></tbody></table></section>
<script>
const timeline=document.querySelector('#timeline'),cards=document.querySelector('#cards'),analyses=document.querySelector('#analyses'),recommendations=document.querySelector('#recommendations'),button=document.querySelector('#run');
const analysisById=new Map();
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const empty=message=>`<p class="empty">${escapeHtml(message)}</p>`;
const emptyRow=message=>`<tr><td colspan="5" class="empty">${escapeHtml(message)}</td></tr>`;
const reset=()=>{button.disabled=false;button.textContent='오늘의 뉴스를 기준으로 추천받기'};
const updateAnalyses=items=>{for(const item of items)analysisById.set(item.id,item);renderAnalyses()};
const renderAnalyses=()=>{const items=[...analysisById.values()];analyses.innerHTML=items.length?items.map(item=>{const events=item.event_titles.length?item.event_titles.map(title=>`<span class="badge">${escapeHtml(title)}</span>`).join(''):'<span class="badge">이벤트 없음</span>';const metrics=item.relevance===null?'':`<p>관련성 ${item.relevance} · 중요도 ${item.importance} · 신뢰도 ${item.credibility}</p>`;const reasons=item.reasons.length?`<p>${item.reasons.map(escapeHtml).join(' · ')}</p>`:'';const validation=item.validation_status?`<p>교차검증: ${escapeHtml(item.validation_status)}</p>`:'';return `<article class="card analysis-card"><small>${escapeHtml(item.source)}</small><h3>${escapeHtml(item.title)}</h3><p><strong>${escapeHtml(item.status)}</strong></p>${item.summary?`<p>${escapeHtml(item.summary)}</p>`:''}<div>${events}</div>${metrics}${reasons}${validation}</article>`}).join(''):empty('수집된 뉴스가 없습니다.')};
async function load(runId){const response=await fetch(`/api/runs/${runId}`);if(!response.ok)throw new Error('result_load_failed');const data=await response.json();analysisById.clear();updateAnalyses(data.analyses);cards.innerHTML=data.news_cards.length?data.news_cards.map(news=>`<article class="card"><small>${escapeHtml(news.source)}</small><h3>${escapeHtml(news.title)}</h3><p>${escapeHtml(news.excerpt)}</p><a href="${escapeHtml(news.url)}" target="_blank" rel="noreferrer">원문 보기</a></article>`).join(''):empty('선택된 뉴스가 없습니다.');recommendations.innerHTML=data.recommendations.length?data.recommendations.map(item=>`<tr><td>${escapeHtml(item.company_name)}</td><td>${escapeHtml(item.ticker||'-')}</td><td>${escapeHtml(item.score)}</td><td class="${item.action.includes('buy')?'buy':item.action.includes('sell')?'sell':''}">${escapeHtml(item.action)}</td><td>${escapeHtml(item.reason_code)}</td></tr>`).join(''):emptyRow('현재 정책 기준을 통과한 추천 종목이 없습니다.')}
button.onclick=async()=>{timeline.innerHTML='';analysisById.clear();renderAnalyses();cards.innerHTML=empty('뉴스를 수집하고 있습니다.');recommendations.innerHTML=emptyRow('추천 분석을 진행하고 있습니다.');button.disabled=true;button.textContent='추천 분석 중…';try{const response=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({limit:3})});if(!response.ok)throw new Error('run_start_failed');const {run_id:runId}=await response.json();let terminal=false;const source=new EventSource(`/api/runs/${runId}/events`);for(const name of ['collecting','collected','directory','workflow','completed','failed'])source.addEventListener(name,async event=>{const data=JSON.parse(event.data);timeline.insertAdjacentHTML('beforeend',`<li>${escapeHtml(data.message)}</li>`);if(data.analyses.length)updateAnalyses(data.analyses);if(data.type==='completed'){terminal=true;source.close();try{await load(runId)}catch(_){cards.innerHTML=empty('결과를 불러오지 못했습니다.');recommendations.innerHTML=emptyRow('결과를 다시 실행해 주세요.')}reset()}if(data.type==='failed'){terminal=true;source.close();cards.innerHTML=empty('뉴스 분석이 완료되지 않았습니다.');recommendations.innerHTML=emptyRow('실행 환경을 확인한 뒤 다시 시도해 주세요.');reset()}});source.onerror=()=>{if(!terminal){source.close();cards.innerHTML=empty('실시간 연결이 끊겼습니다.');recommendations.innerHTML=emptyRow('다시 실행해 주세요.');reset()}}}catch(_){cards.innerHTML=empty('추천 실행을 시작하지 못했습니다.');recommendations.innerHTML=emptyRow('잠시 후 다시 시도해 주세요.');reset()}};
</script></main></body></html>"""
