"""Password-gated static client for the KST scheduled recommendation settings."""

from __future__ import annotations


SCHEDULE_SETTINGS_HTML: str = """<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><title>정기 실행 설정</title>
<style>:root{color-scheme:dark}body{font-family:system-ui;background:#07111e;color:#edf3ff;margin:0}main{max-width:720px;margin:auto;padding:32px}.panel{background:#101d2d;border:1px solid #253852;border-radius:12px;padding:20px;margin:18px 0}label{display:block;margin:12px 0}input,select{box-sizing:border-box;width:100%;padding:10px;margin-top:5px;border-radius:7px;border:1px solid #385474;background:#07111e;color:#edf3ff}button{background:#4f8cff;color:#fff;border:0;border-radius:8px;padding:11px 16px;font-weight:700;cursor:pointer}.hidden{display:none}.note{color:#aec0d8}.error{color:#ff9aa8}</style>
</head><body><main><h1>정기 실행 설정</h1><p class="note">RSS 기반 추천 작업의 cron은 한국시간 기준입니다. 비밀번호는 로그인 요청에만 사용하며 브라우저에 저장하지 않습니다.</p>
<section id="login-panel" class="panel"><h2>접근 확인</h2><label>설정 비밀번호<input id="password" type="password" autocomplete="current-password"></label><button id="login" type="button">설정 페이지 열기</button><p id="login-status" class="error"></p></section>
<section id="settings-panel" class="panel hidden"><h2>실행 조건</h2><label><input id="active" type="checkbox" checked> 정기 실행 활성화</label><label>cron 표현식<input id="cron" value="0 8 * * *" maxlength="128" required></label><label>분석 건수<select id="limit"><option value="25">25건</option><option value="50">50건</option><option value="100">100건</option></select></label><fieldset><legend>투자 테마</legend><label><input class="theme" value="semiconductor" type="checkbox"> 반도체</label><label><input class="theme" value="artificial_intelligence" type="checkbox"> AI</label><label><input class="theme" value="renewable_energy" type="checkbox"> 대체에너지</label></fieldset><fieldset><legend>뉴스 주제</legend><label><input class="topic" value="earnings" type="checkbox"> 실적</label><label><input class="topic" value="policy" type="checkbox"> 정책</label><label><input class="topic" value="supply_chain" type="checkbox"> 공급망</label><label><input class="topic" value="technology" type="checkbox"> 기술</label></fieldset><label><input id="telegram" type="checkbox"> Telegram 요약 전송</label><p class="note">Telegram 자격 증명은 서버 `.env`의 `TELEGRAM_BOT_TOKEN`, `TELEGRAM_CHAT_ID`로만 설정합니다.</p><button id="save" type="button">저장</button><p id="save-status" class="note"></p></section>
<p><a href="/">대시보드로 돌아가기</a></p>
<script>
let scheduleVersion=null;const loginPanel=document.querySelector('#login-panel'),settingsPanel=document.querySelector('#settings-panel'),password=document.querySelector('#password'),login=document.querySelector('#login'),loginStatus=document.querySelector('#login-status'),active=document.querySelector('#active'),cron=document.querySelector('#cron'),limit=document.querySelector('#limit'),telegram=document.querySelector('#telegram'),save=document.querySelector('#save'),saveStatus=document.querySelector('#save-status'),themes=[...document.querySelectorAll('.theme')],topics=[...document.querySelectorAll('.topic')];
const selected=items=>items.filter(item=>item.checked).map(item=>item.value);const restore=(items,values)=>items.forEach(item=>item.checked=values.includes(item.value));
async function load(){const response=await fetch('/api/settings/schedule');if(response.status===404){settingsPanel.classList.remove('hidden');return}if(!response.ok)throw new Error('schedule_load_failed');const value=await response.json();scheduleVersion=value.version;active.checked=value.active;cron.value=value.cron_expression;limit.value=String(value.limit);restore(themes,value.themes);restore(topics,value.topics);telegram.checked=value.telegram_enabled;settingsPanel.classList.remove('hidden');saveStatus.textContent=`저장됨 · 다음 실행 ${new Date(value.next_run_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST`}
login.onclick=async()=>{loginStatus.textContent='';const response=await fetch('/api/settings/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:password.value})});password.value='';if(!response.ok){loginStatus.textContent='비밀번호가 일치하지 않거나 서버 설정이 완료되지 않았습니다.';return}loginPanel.classList.add('hidden');try{await load()}catch(_){loginStatus.textContent='설정 정보를 불러오지 못했습니다.'}};
save.onclick=async()=>{const response=await fetch('/api/settings/schedule',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({active:active.checked,cron_expression:cron.value,themes:selected(themes),topics:selected(topics),limit:Number(limit.value),telegram_enabled:telegram.checked,version:scheduleVersion})});if(response.status===409){saveStatus.textContent='다른 화면에서 설정이 변경되었습니다. 새로고침 후 다시 저장해 주세요.';return}if(!response.ok){saveStatus.textContent='저장에 실패했습니다. cron 및 서버 연결을 확인해 주세요.';return}const value=await response.json();scheduleVersion=value.version;saveStatus.textContent=`저장됨 · 다음 실행 ${new Date(value.next_run_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST`};
</script></main></body></html>"""
